name: Howdy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
     
    - name: Send me a text
      env:
        ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        TWILIO_NO: ${{ secrets.TWILIO_NO }}
        MY_NO: ${{ secrets.MY_NO }}
      run: |
        pip install setuptools twilio
        python3 textmemaybe.py
