name: Howdy
on: [push]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Echo the greeting's time
        run: |
          pip install -r requirements.txt
          python textmemaybe.py
